name: format

on:
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: black
        uses: psf/black@stable
        with:
          options: ""
          src: "."

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style(format): run black"

      - name: isort
        uses: isort/isort-action@master
        with:
          configuration: ""
          sortPaths: "."

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style(format): run isort"
